spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://newstwindatabase.cdescwsyqo0x.ap-northeast-2.rds.amazonaws.com:5432/newstwindb
    username: newstwin
    password: sbtmxmdnls!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # 엔티티와 DB 구조 검증
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# AWS 설정
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ap-northeast-2
  s3:
    bucket-name: newstwin-pjt-bucket